# Generated by Django 3.1.1 on 2020-09-25 14:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
