# Generated by Django 3.1.1 on 2020-09-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_compra_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earnings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unique_clients', models.IntegerField()),
                ('avg_profit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
